server:
  port: 38762
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/fitzMeng/config-repo
          username: mzh950810@gmail.com
          password: mzh19950810
          basedir: ./config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:38761/eureka/
  instance:
    prefer-ip-address: true